apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: builder-image-aws
    context: ./builder-image-aws
  - image: build-image-gradle
    context: ./builder-image-gradle
  - image: builder-image-maven
    context: ./builder-image-maven
  - image: builder-image-openshift
    context: ./builder-image-openshift
  - image: builder-image-skaffold
    context: ./builder-image-skaffold
  - image: builder-image-terraform
    context: ./builder-image-terraform
  - image: builder-image-gitops
    context: ./builder-image-gitops
  - image: jenkins-image
    context: ./jenkins-image

test:
- image: builder-image-aws
  structureTests:
  - ./builder-image-aws/test/*
- image: build-image-gradle
  structureTests:
  - ./builder-image-gradle/test/*
- image: build-image-ruby
  structureTests:
  - ./builder-image-ruby/test/*
- image: builder-image-maven
  structureTests:
  - ./builder-image-maven/test/*
- image: builder-image-aws
  structureTests:
  - ./builder-image-aws/test/*
- image: builder-image-openshift
  structureTests:
  - ./builder-image-openshift/test/*
- image: builder-image-skaffold
  structureTests:
  - ./builder-image-skaffold/test/*
- image: builder-image-terraform
  structureTests:
  - ./builder-image-terraform/test/*
